# Generated by Django 5.1.4 on 2025-01-07 20:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AddField(
            model_name='project',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.TextField(default='Short description of the project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
