# Generated by Django 5.1.5 on 2026-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experience_delete_social_remove_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_me_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='current_role_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
