# Generated by Django 5.1.4 on 2025-01-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_about_delete_social_project_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='resume',
        ),
    ]
