# Generated by Django 5.1.4 on 2025-01-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Longer description of the project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(default='Technologies used in the project'),
        ),
    ]
