# Generated by Django 6.0.7 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_about_rich_text_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_me_body',
        ),
        migrations.RemoveField(
            model_name='about',
            name='current_role_body',
        ),
        migrations.AddField(
            model_name='about',
            name='availability_text',
            field=models.CharField(blank=True, default='Open to 2026–27 opportunities', max_length=120),
        ),
        migrations.AddField(
            model_name='about',
            name='current_focus_category',
            field=models.CharField(blank=True, default='Research', max_length=80),
        ),
        migrations.AddField(
            model_name='about',
            name='current_focus_label',
            field=models.CharField(blank=True, default='Currently exploring', max_length=80),
        ),
        migrations.AddField(
            model_name='about',
            name='current_focus_organization',
            field=models.CharField(blank=True, default='UCF', max_length=80),
        ),
        migrations.AddField(
            model_name='about',
            name='current_focus_period',
            field=models.CharField(blank=True, default='2024 to present', max_length=80),
        ),
        migrations.AddField(
            model_name='about',
            name='current_focus_title',
            field=models.CharField(blank=True, default='Multi-agent reinforcement learning', max_length=180),
        ),
        migrations.AddField(
            model_name='about',
            name='location_latitude',
            field=models.CharField(blank=True, default='28.5383° N', max_length=40),
        ),
        migrations.AddField(
            model_name='about',
            name='location_longitude',
            field=models.CharField(blank=True, default='81.3792° W', max_length=40),
        ),
    ]
