# Generated by Django 5.1.4 on 2025-01-08 02:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_about_github_dark_about_github_light_about_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=api.models.About.resume_upload_to),
        ),
    ]
