# Generated by Django 5.1.5 on 2025-01-19 19:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_about_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.About.image_1_upload_to),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.About.image_2_upload_to),
        ),
        migrations.AlterField(
            model_name='about',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.About.image_3_upload_to),
        ),
        migrations.AlterField(
            model_name='about',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.About.image_4_upload_to),
        ),
    ]
