# Generated by Django 5.1.5 on 2025-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_about_image1_alter_about_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='About Me', max_length=100),
        ),
    ]
