# Generated by Django 5.1.5 on 2025-01-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('start_mthyr', models.CharField(max_length=100)),
                ('end_mthyr', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description of the experience')),
            ],
        ),
    ]
