name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private_key
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy to EC2
        env:
          EC2_HOST: 52.204.158.12
          EC2_USER: ubuntu
        run: |
          ssh -i ~/.ssh/private_key $EC2_USER@$EC2_HOST <<EOF
            cd /home/ubuntu/personal-portfolio
            git pull origin main
            cd backend
            source webenv/bin/activate
            pip install -r req.txt
            cd ../wed-front
            npm install
            npm run build
            sudo rm -rf /var/www/vhosts/frontend/*
            sudo cp -r dist/* /var/www/vhosts/frontend/
            sudo chown -R www-data:www-data /var/www/vhosts/frontend/
            sudo chmod -R 755 /var/www/vhosts/frontend/
            sudo systemctl daemon-reload
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
          EOF