name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 52.204.158.12 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -v ubuntu@52.204.158.12 "echo Connection successful"

      - name: Deploy to EC2
        if: success()
        run: |
          ssh ubuntu@52.204.158.12 <<EOF
            set -e
            echo "Starting deployment..."
            cd /home/ubuntu/personal-portfolio
            git pull origin main
            cd backend
            source webenv/bin/activate
            pip install -r req.txt
            cd ../wed-front
            npm install
            npm run build
            sudo rm -rf /var/www/vhosts/frontend*
            sudo cp -r dist/* /var/www/vhosts/frontend
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl daemon-reload
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
            echo "Deployment completed successfully!"
          EOF


          