name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H 52.204.158.12 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -v -i ~/.ssh/id_ed25519 ubuntu@52.204.158.12 "echo Connection successful"

      - name: Deploy to EC2
        if: success()
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@52.204.158.12 <<EOF
            set -e
            echo "Starting deployment..."
            cd /home/ubuntu/personal-portfolio
            git pull origin main
            cd backend
            source webenv/bin/activate
            pip install -r req.txt
            cd ../wed-front
            npm install
            npm run build
            sudo rm -rf /var/www/vhosts/frontend*
            sudo cp -r dist/* /var/www/vhosts/frontend
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl daemon-reload
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
            echo "Deployment completed successfully!"
          EOF